---

- name: Remove all crap from Dock
  shell: dockutil --remove '{{ item }}'
  ignore_errors: true
  loop: "{{ config.dockitems.remove }}"
  when: config.dockitems is defined

- name: Cleanup spacers
  shell: dockutil --remove spacer-tiles
  when: config.dockitems is defined

- name: Add dock items
  shell: dockutil --find '{{ item.name }}' || dockutil --add '{{ item.path }}'
  loop: "{{ config.dockitems.exists }}"
  when: config.dockitems is defined

- name: Fix order
  shell: dockutil --move '{{ item.name }}' --position {{ index + 1 }}
  loop: "{{ config.dockitems.exists }}"
  loop_control:
    index_var: index
  when: config.dockitems is defined

- name: Add spacers
  shell: dockutil --add '' --type spacer --section apps --after '{{ item.name }}'
  loop: "{{ config.dockitems.exists }}"
  when: 
    - config.dockitems is defined
    - "'with_spacer' in item"
