---
- name: Ensure .config dir
  tags: ["symlinks", "templates"]
  file:
    path: '~/.config'
    state: directory

# TODO: move to better place
- name: Ensure kitty config dir
  tags: ["symlinks", "templates"]
  file:
    path: '~/.config/kitty'
    state: directory

- name: Ensure nvim config dir
  tags: ["symlinks", "templates"]
  file:
    path: '~/.config/nvim'
    state: directory
# END_TODO

- name: Create symlinks
  tags: ["symlinks"]
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dst }}'
    state: link
  with_items: "{{ config.symlinks }}"
  when: config.symlinks is defined

- name: Template dotfiles
  tags: ["templates"]
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dst }}'
  with_items: "{{ config.templates }}"
  when: config.templates is defined

- name: Ensure scripts dir
  tags: ["scripts"]
  file:
    path: '~/.scripts'
    state: directory

- name: Link scripts
  tags: ["scripts"]
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dst }}'
    state: link
    mode: '0744'
  with_items: "{{ config.scripts }}"
  when: config.scripts is defined
